version: '3'

services:
  portainer:
    image: drone/drone:1.0.0-rc.5
    command: -H unix:///var/run/docker.sock
    restart: always
    container_name: drone
    networks:
      - traefik
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /var/lib/drone:/data
    environment:
      - DRONE_GITHUB_SERVER=https://github.com
      - DRONE_GITHUB_CLIENT_ID=${DRONE_GITHUB_CLIENT_ID}
      - DRONE_GITHUB_CLIENT_SECRET=${DRONE_GITHUB_CLIENT_SECRET}
      - DRONE_RUNNER_CAPACITY=2
      - DRONE_SERVER_HOST=${DRONE_SERVER_HOST}
      - DRONE_SERVER_PROTO=${DRONE_SERVER_PROTO}
      - DRONE_TLS_AUTOCERT=true
      - DRONE_GIT_ALWAYS_AUTH=false
      - DRONE_USER_CREATE=username:${DRONE_USER_CREATE_USERNAME},admin:true
    labels:
      - traefik.backend=drone
      - traefik.docker.network=traefik
      - traefik.enable=true
      - traefik.frontend.rule=Host:${DRONE_SERVER_HOST}
      - traefik.port=80

networks:
  traefik:
    external: true